[project]
name = "egs-free-games-scraper"
version = "0.1.0"
description = "Web Scraper of free games from Epic Games Store"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.4.1",
    "selenium>=4.34.2",
]
